import "./globals.css";
import Navbar from "@/components/shared/Navbar";

export const metadata = {
    title: "Jasir | Software Engineer",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Navbar/>
        {children}
        </body>
        </html>
    );
}
